apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rest-api.fullname" . }}-nginx
  labels:
    {{- include "rest-api.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen {{ .Values.app.listenPort }};
        server_name _;

        location / {
            return 200 '{"status": "running"}';
            add_header Content-Type application/json;
        }

        location /health {
            access_log off;
            return 200 '{"status": "healthy"}';
            add_header Content-Type application/json;
        }
    }
