apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rest-api.fullname" . }}
  labels:
    {{- include "rest-api.labels" . | nindent 4 }}
data:
  LISTEN_HOST: {{ .Values.app.listenHost | quote }}
  LISTEN_PORT: {{ .Values.app.listenPort | quote }}
  {{- range $key, $value := .Values.app.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
